import { Router } from "express";
import { productController } from "../../controllers/apis/product.controller.js";

const router = Router();

/**
 * @swagger
 * tags:
 *   name: Products
 *   description: Product management
 */

/**
 * @swagger
 * /api/products:
 *   post:
 *     summary: Create a product
 *     tags: [Products]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               name:
 *                 type: string
 *               description:
 *                 type: string
 *               detailDescription:
 *                 type: string
 *               price:
 *                 type: number
 *                 format: float
 *               category:
 *                 type: string
 *               imageUrl:
 *                 type: string
 *               stock:
 *                 type: integer
 *     responses:
 *       201:
 *         description: Product created successfully
 *       400:
 *         description: Bad request
 */
router.post("/", productController.createProduct);

/**
 * @swagger
 * /api/products:
 *   get:
 *     summary: Get all products
 *     tags: [Products]
 *     parameters:
 *       - in: query
 *         name: page
 *         required: false
 *         schema:
 *           type: integer
 *           default: 1
 *       - in: query
 *         name: limit
 *         required: false
 *         schema:
 *           type: integer
 *           default: 10
 *       - in: query
 *         name: category
 *         required: false
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: List of products
 *       404:
 *         description: Products not found
 */
router.get("/", productController.getAllProducts);
/**
 * @swagger
 * /api/products/revenue:
 *   get:
 *     summary: Get top 10 products sorted by total revenue within a specified time range
 *     tags: [Products]
 *     parameters:
 *       - in: query
 *         name: start
 *         schema:
 *           type: integer
 *           format: int64
 *           description: Start of the time range in milliseconds since Unix epoch (inclusive).
 *         required: true
 *       - in: query
 *         name: end
 *         schema:
 *           type: integer
 *           format: int64
 *           description: End of the time range in milliseconds since Unix epoch (inclusive).
 *         required: true
 *     responses:
 *       200:
 *         description: List of top 10 products with total revenue info within the specified time range.
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   _id:
 *                     type: string
 *                     description: Product ID
 *                   name:
 *                     type: string
 *                     description: Product name
 *                   price:
 *                     type: number
 *                     format: double
 *                     description: Product price
 *                   totalRevenue:
 *                     type: number
 *                     format: double
 *                     description: Total revenue generated by the product within the time range
 *       400:
 *         description: Bad request (e.g., missing or invalid query parameters)
 */
router.get("/revenue", productController.getProductsWithRevenue);

/**
 * @swagger
 * /api/products/{id}/comments:
 *   get:
 *     summary: Get comments for a product
 *     tags: [Products, Comments]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *           description: Product ID
 *       - in: query
 *         name: page
 *         required: false
 *         schema:
 *           type: integer
 *           default: 1
 *       - in: query
 *         name: limit
 *         required: false
 *         schema:
 *           type: integer
 *           default: 10
 *     responses:
 *       200:
 *         description: List of comments for the product
 *       404:
 *         description: Product not found
 */
router.get("/:id/comments", productController.getCommentsByProduct);

/**
 * @swagger
 * /api/products/{id}/comments:
 *   post:
 *     summary: Post a comment on a product
 *     tags: [Products, Comments]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *           description: Product ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               content:
 *                 type: string
 *                 description: Comment content
 *               rating:
 *                 type: number
 *                 format: float
 *                 description: Rating for the product
 *     responses:
 *       201:
 *         description: Comment created successfully
 *       400:
 *         description: Bad request
 */
router.post("/:id/comments", productController.postComment);

/**
 * @swagger
 * /api/products/{id}:
 *   get:
 *     summary: Get a product by ID
 *     tags: [Products]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         description: Product ID
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Product found
 *       404:
 *         description: Product not found
 */

router.get("/:id", productController.getProduct);

/**
 * @swagger
 * /api/products/{id}:
 *   delete:
 *     summary: Delete a product by ID
 *     tags: [Products]
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         description: Product ID
 *         schema:
 *           type: string
 *     responses:
 *       204:
 *         description: Product deleted successfully
 *       404:
 *         description: Product not found
 */
router.delete("/:id", productController.deleteProduct);

/**
 * @swagger
 * /api/products/{id}:
 *   patch:
 *     summary: Update a product
 *     tags: [Products]
 *     parameters:
 *       - in: path
 *         name: id
 *         schema:
 *           type: string
 *         required: true
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               name:
 *                 type: string
 *               description:
 *                 type: string
 *               detailDescription:
 *                 type: string
 *               price:
 *                 type: number
 *                 format: float
 *               promotePrice:
 *                 type: number
 *                 format: float
 *               category:
 *                 type: string
 *               imageUrl:
 *                 type: string
 *               stock:
 *                 type: integer
 *     responses:
 *       200:
 *         description: Product updated successfully
 *       400:
 *         description: Bad request
 *       404:
 *         description: Product not found
 */
router.patch("/:id", productController.updateProduct);

export default router;
